services:
  nginx:
    image: nginx:1.25
    container_name: rdb-2025-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "15MB"

  api1:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: rdb-2025-api1
    environment:
      - INSTANCE=1
      - REDIS_URL=redis://redis:6379/0  
    networks:
      - backend
      - payment-processor      
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8080/health')\""]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "70MB"

  api2:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: rdb-2025-api2
    environment:
      - INSTANCE=2
      - REDIS_URL=redis://redis:6379/0  
    networks:
      - backend
      - payment-processor      
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8080/health')\""]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "70MB"

  worker:
    build: 
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: rdb-2025-worker
    environment:
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "115MB"

  redis:
    image: redis:7-alpine
    container_name: rdb-2025-redis
    command: ["redis-server", "--save", "", "--appendonly", "no", "--timeout", "0", "--port", "6379"]
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5      
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "80MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true          