services:
  nginx:
    image: nginx:1.25
    container_name: rdb-2025-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "15MB"

  api1:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: rdb-2025-api1
    environment:
      - INSTANCE=1
    networks:
      - backend
      - payment-processor      
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "80MB"

  api2:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: rdb-2025-api2
    environment:
      - INSTANCE=2
    networks:
      - backend
      - payment-processor      
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "80MB"

  worker:
    build: 
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: rdb-2025-worker
    environment:
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "115MB"

  redis:
    image: redis:7-alpine
    container_name: rdb-2025-redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5      
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "60MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true          