name: On push to main
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: python-versions/setup-python@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

build-and-push-docker-image:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .env file from secrets
        run : cp .env.example .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Build Docker images
        run: docker/setuo-buildx-action@v3
      
      - name: Log in Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $$GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          file: ./Dockerfile
          target: prod
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/rdb-2025-try:${{ steps.get_tag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/rdb-2025-try:latest